package gui.messageHandler;

public enum MessageType {
	
	FILE_NOT_FOUND, NO_COMPONENT_SELECTED, PARAMETAR_SELECTED, SERIALISATION_FAIL, DESERIALISATION_FAIL, WRONG_COMPONENT_SELECTED,
	PROGRAM_START, CLOSING, NODE_REMOVAL

}
