package gui.messageHandler;

public enum MessageType {
	
	FILE_NOT_FOUND, NO_COMPONENT_SELECTED, PARAMETAR_SELECTED, SERIALISATION_FAIL, DESERIALISATION_FAIL, WRONG_COMPONENT_SELECTED_PARAMETAR, 
	WRONG_COMPONENT_SELECTED_PRODUCT, PROGRAM_START, CLOSING, NODE_REMOVAL, WRONG_FILE_SELECTED
}
