package gui.messageHandler;

public enum MessageType {
	
	FILE_NOT_FOUND, NO_COMPONENT_SELECTED, PARAMETAR_SELECTED, SERIALISATION_FAIL, DESERIALISATION_FAIL, WRONG_COMPONENT_SELECTED_PARAMETAR, 
	WRONG_COMPONENT_SELECTED_PRODUCT, PROGRAM_START, CLOSING, NODE_REMOVAL, CLIPBOARD_EMPTY, WRONG_TYPE_IN_CLIPBOARD, WRONG_TYPE_TO_COPY, CONNECTION_FAILED
}
